//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 09:18:15 PM EET 
//


package ua.kpi.epam.xmlproject.warplanes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="warplane" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="chars">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="type">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="���������"/>
 *                                   &lt;enumeration value="�������������"/>
 *                                   &lt;enumeration value="�����������"/>
 *                                   &lt;enumeration value="�����������"/>
 *                                   &lt;enumeration value="���������"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="rocket" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="radar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="parameters">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="price" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "warplane"
})
@XmlRootElement(name = "warplane-list")
public class WarplaneList {

    @XmlElement(required = true)
    protected List<WarplaneList.Warplane> warplane;

    /**
     * Gets the value of the warplane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warplane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarplane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WarplaneList.Warplane }
     * 
     * 
     */
    public List<WarplaneList.Warplane> getWarplane() {
        if (warplane == null) {
            warplane = new ArrayList<WarplaneList.Warplane>();
        }
        return this.warplane;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="chars">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="type">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="���������"/>
     *                         &lt;enumeration value="�������������"/>
     *                         &lt;enumeration value="�����������"/>
     *                         &lt;enumeration value="�����������"/>
     *                         &lt;enumeration value="���������"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="rocket" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="radar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="parameters">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="price" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "origin",
        "chars",
        "parameters"
    })
    public static class Warplane {

        @XmlElement(required = true)
        protected String origin;
        @XmlElement(required = true)
        protected WarplaneList.Warplane.Chars chars;
        @XmlElement(required = true)
        protected WarplaneList.Warplane.Parameters parameters;
        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute(required = true)
        protected int price;

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the chars property.
         * 
         * @return
         *     possible object is
         *     {@link WarplaneList.Warplane.Chars }
         *     
         */
        public WarplaneList.Warplane.Chars getChars() {
            return chars;
        }

        /**
         * Sets the value of the chars property.
         * 
         * @param value
         *     allowed object is
         *     {@link WarplaneList.Warplane.Chars }
         *     
         */
        public void setChars(WarplaneList.Warplane.Chars value) {
            this.chars = value;
        }

        /**
         * Gets the value of the parameters property.
         * 
         * @return
         *     possible object is
         *     {@link WarplaneList.Warplane.Parameters }
         *     
         */
        public WarplaneList.Warplane.Parameters getParameters() {
            return parameters;
        }

        /**
         * Sets the value of the parameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link WarplaneList.Warplane.Parameters }
         *     
         */
        public void setParameters(WarplaneList.Warplane.Parameters value) {
            this.parameters = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the price property.
         * 
         */
        public int getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         */
        public void setPrice(int value) {
            this.price = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="type">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="���������"/>
         *               &lt;enumeration value="�������������"/>
         *               &lt;enumeration value="�����������"/>
         *               &lt;enumeration value="�����������"/>
         *               &lt;enumeration value="���������"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="rocket" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="radar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "places",
            "rocket",
            "radar"
        })
        public static class Chars {

            @XmlElement(required = true)
            protected String type;
            protected byte places;
            protected Byte rocket;
            protected boolean radar;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the places property.
             * 
             */
            public byte getPlaces() {
                return places;
            }

            /**
             * Sets the value of the places property.
             * 
             */
            public void setPlaces(byte value) {
                this.places = value;
            }

            /**
             * Gets the value of the rocket property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getRocket() {
                return rocket;
            }

            /**
             * Sets the value of the rocket property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setRocket(Byte value) {
                this.rocket = value;
            }

            /**
             * Gets the value of the radar property.
             * 
             */
            public boolean isRadar() {
                return radar;
            }

            /**
             * Sets the value of the radar property.
             * 
             */
            public void setRadar(boolean value) {
                this.radar = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "length",
            "width",
            "height"
        })
        public static class Parameters {

            protected float length;
            protected float width;
            protected float height;

            /**
             * Gets the value of the length property.
             * 
             */
            public float getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             */
            public void setLength(float value) {
                this.length = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public float getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(float value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public float getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(float value) {
                this.height = value;
            }

        }

    }

}
